<a href="https://colab.research.google.com/github/i-ninte/machine_learning/blob/main/handwriting_recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install --upgrade pip


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 24.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [3]:
!apt update
!apt upgrade


Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease [18.1 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,005 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,270 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,082 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,347 kB]
Hit:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpa

In [4]:
!pip install scikit-learn


In [5]:
pip install pillow

In [6]:
pip install mnist

In [ ]:
#next we download gimp from google and create a 28 * 28	image
# a python program that gives the pixel and we give that pixel to our model and hopefully it returns the number we wrote with gimp
#image to bytes
from PIL import Image
img = Image.open("img.xcf")
data= list(img.getdata())
print(data)


# after viewing our data we found out that it is the opposite of the data we had in our dataset. ous started with all 0s but this starts with all 1s


#converting the data to suit ours
for i in range(len(data)):
	data[i]= 255- data[i]
print(data)

#after running the program we copy the data and store it ina variable called five

five=np.array(five)/256
#divifing by 256 to convert them within the data range
p= clf.predict([five])
print(p)

In [10]:
import tensorflow as tf
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

# Load the MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the pixel values
x_train, x_test = x_train / 255.0, x_test / 255.0

# Flatten the image data
x_train = x_train.reshape(x_train.shape[0], -1)
x_test = x_test.reshape(x_test.shape[0], -1)

# Create and train your MLPClassifier
clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64, 64))
clf.fit(x_train, y_train)

# Make predictions and calculate accuracy
predictions = clf.predict(x_test)
accuracy = confusion_matrix(y_test, predictions)
print(accuracy)


11490434/11490434 [==============================] - 0s 0us/step
[[ 968    0    2    3    1    1    1    0    2    2]
 [   0 1123    3    1    0    1    2    1    4    0]
 [   3    2 1012    3    1    0    1    4    6    0]
 [   0    0    1  991    1    5    0    2    3    7]
 [   1    0    3    0  953    2    4    4    1   14]
 [   2    0    0    7    1  866    3    1    7    5]
 [   4    2    3    1    7    6  932    0    3    0]
 [   1    7    8    1    1    0    0 1001    3    6]
 [   7    0    2    6    5    8    2    2  938    4]
 [   3    2    1    3   10    5    0    9    0  976]]


In [18]:
from PIL import Image
import numpy as np

# Load the image in a common format (e.g., PNG or JPG)
img = Image.open('img.jpg')

# Convert the image to grayscale (if not already)
img = img.convert('L')

# Resize the image to 28x28 pixels (if not already)
img = img.resize((28, 28))

# Convert the image data to a numpy array
data = np.array(img)

data = 255 - data

# Normalize the pixel values to be in the range [0, 1]
data = data / 255.0

data = data.reshape(1, -1)

# Use your trained model to make predictions
prediction = clf.predict(data)

# Print the predicted number
print("Predicted Number:", prediction[0])


Predicted Number: 2
