<a href="https://colab.research.google.com/github/i-ninte/machine_learning/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install sklearn

  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post9-py3-none-any.whl size=2952 sha256=b927e48e4c06b7bdc719732c688a112fd5988d171f36a9c221725d5e57da3a04
  Stored in directory: /root/.cache/pip/wheels/33/a3/d2/092b519e9522b4c91608b7dcec0dd9051fa1bff4c45f4502d1
Successfully built sklearn


In [10]:
import pandas as pd
import numpy as np
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


data = pd.read_csv("car.data")
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [11]:
data.shape

(1728, 7)

column names are buying, maint,(maintenace), doors, persons, lug_boot, safety, class

In [13]:
# creating labels and features
#features
X= data[['buying','maint','safety' ]].values

# labels
y=data[['class']]

print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


But for the machine learning model to be able to work, it has to work with numbers and not strings hence we would have to convet the strings to numbers

In [14]:
#converting features(X)
Le= LabelEncoder()
for i  in range(len(X[0])):
  X[:,i] = Le.fit_transform(X[:,i])

print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


converting the labels(y) using mapping

In [15]:
label_mapping= {
    'unacc': 0,
    'acc':1,
    'good':2,
    'vgood':3

}

y['class']= y['class'].map(label_mapping)
# converting y to a numpy array
y= np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-15-83db58bf1a9a>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']= y['class'].map(label_mapping)


In [17]:
#creating model
knn= neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

#separating the model into training and testingn data
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2)

#training the model(fitiing )

knn.fit(X_train, y_train)

# making predictions
prediction = knn.predict(X_test)

# checking the performance of the knn model
accuracy = metrics.accuracy_score(y_test, prediction)

print("predictions", prediction)
print("accuracy", accuracy)

predictions [0 0 0 0 0 2 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 3 0 0 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 2 0 0 0 0 2 0 0 0 1 0 0 3 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 1 0 3 0 0 0 0 0 3 1
 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 2 0 0 1 0 0 2 1 1 0 0 1 0 0 1 0 0 1 0 1
 0 0 0 0 0 0 1 0 1 0 0 2 0 0 0 1 0 0 0 3 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0
 0 0 0 1 3 0 1 0 1 0 0 3 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0
 3 0 0 1 0 0 0 0 0 0 3 0 0 3 0 0 0 1 0 0 0 0 0 0 1 0 0 3 0 0 0 2 1 1 0 0 1
 0 0 0 0 0 0 1 0 0 0 1 0 0 0 3 0 0 0 0 1 0 2 0 0 2 0 0 0 0 0 1 1 0 1 1 0 0
 1 0 0 0 0 1 1 3 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 3 1 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 1]
accuracy 0.7398843930635838


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [19]:
# Testing the model
print("Actual value:", y[20])  # Accessing actual value by index
print("Predicted value:", knn.predict(X)[20])  # Accessing predicted value by index


Actual value: [0]
Predicted value: 0
